In [1]:
import pandas as pd
import json

In [2]:
google_countries = pd.read_csv('countries.csv',encoding='utf-8')

In [3]:
google_names = google_countries.values[:,3]

In [4]:
es_data = {}
with open('esCountries.json') as json_file:  
    es_data = json.load(json_file)

In [5]:
es_names = [i['key'] for i in es_data["aggregations"]["tags"]["buckets"]]

In [6]:
not_in_google = []
index = []
for name in es_names:
    try:
        index.append(google_names.tolist().index(name))
    except:
        not_in_google.append(name)

In [7]:
def printer():
    for i in not_in_google:
        print(" -> " + i )
printer()

 -> Republic of Korea
 -> Czechia
 -> Republic of Lithuania
 -> Republic of Moldova
 -> Hashemite Kingdom of Jordan
 -> Myanmar
 -> Macedonia
 -> Macao
 -> Curaçao
 -> Palestine
 -> St Kitts and Nevis
 -> Sint Maarten
 -> Ivory Coast
 -> Bonaire, Sint Eustatius, and Saba
 -> Congo
 -> Cabo Verde
 -> Åland
 -> Saint Martin
 -> Eswatini
 -> Saint Barthélemy
 -> Federated States of Micronesia
 -> Republic of the Congo
 -> Democratic Republic of Timor-Leste
 -> South Sudan
 -> Falkland Islands

South Korea -> Republic of Korea +
Czech Republic -> Czechia +
Lithuania -> Republic of Lithuania +
Moldova -> Republic of Moldova
Jordan -> Hashemite Kingdom of Jordan
Myanmar [Burma] -> Myanmar
Macedonia [FYROM] -> Macedonia
Macau -> Macao
     ?no -> Curaçao
Palestinian Territories -> Palestine
Saint Kitts and Nevis -> St Kitts and Nevis
     no? -> Sint Maarten
Côte d'Ivoire -> Ivory Coast
     no? -> Bonaire, Sint Eustatius, and Saba
хз яке конго норм -> Congo
Cape Verde -> Cabo Verde
     no? -> Åland
     no? -> Saint Martin
Swaziland -> Eswatini
     no? -> Saint Barthélemy
Micronesia -> Federated States of Micronesia
Congo [DRC] -> Republic of the Congo
Timor-Leste -> Democratic Republic of Timor-Leste
     no? -> South Sudan
Falkland Islands [Islas Malvinas] -> Falkland Islands

In [8]:
len(not_in_google)

25

In [9]:
len(index)

220

In [10]:
def replacer(old_name, new_name):
    google_countries.loc[google_countries['name'] == old_name, 'name'] = new_name

In [11]:
to_replace = [[u'South Korea' , u'Republic of Korea'],
[u'Czech Republic' , u'Czechia'],
[u'Lithuania' , u'Republic of Lithuania'],
[u'Moldova' , u'Republic of Moldova'],
[u'Jordan' , u'Hashemite Kingdom of Jordan'],
[u'Myanmar [Burma]' , u'Myanmar'],
[u'Macedonia [FYROM]' , u'Macedonia'],
[u'Macau' , u'Macao'],
[u'Palestinian Territories' , u'Palestine'],
[u'Saint Kitts and Nevis' , u'St Kitts and Nevis'],
[u"Côte d'Ivoire" , u'Ivory Coast'], #don't work
[u'Cape Verde' , u'Cabo Verde'],
[u'Swaziland' , u'Eswatini'],
[u'Micronesia' , u'Federated States of Micronesia'],
[u'Timor-Leste' , u'Democratic Republic of Timor-Leste'],
[u'Falkland Islands [Islas Malvinas]' , u'Falkland Islands']]

In [12]:
for item in to_replace:
    replacer(item[0],item[1])

In [13]:
replacer('Congo [DRC]','Congo')
replacer('Congo [Republic]','Republic of the Congo')

In [14]:
google_names = google_countries.values[:,3]
not_in_google = []
index = []
for name in es_names:
    try:
        index.append(google_names.tolist().index(name))
    except:
        not_in_google.append(name)

In [15]:
printer()

 -> Curaçao
 -> Sint Maarten
 -> Bonaire, Sint Eustatius, and Saba
 -> Åland
 -> Saint Martin
 -> Saint Barthélemy
 -> South Sudan

In [16]:
new_data = [
    [u'CW',12.116667,-68.933333,u'Curaçao'],
    [u'SX',18.033333,-63.05,u'Sint Maarten'],
    [u'BQ',12.183333,-68.233333,u'Bonaire, Sint Eustatius, and Saba'],
    [u'AX',60.116667,19.9,u'Åland'],
    [u'Empty',18.066667,-63.05,u'Saint Martin'],
    [u'Nan',17.9,-62.833333,u'Saint Barthélemy'],
    [u'SS',4.85,31.6,u'South Sudan'],
]

In [17]:
for item in new_data:
    google_countries = google_countries.append({'country': item[0], 'latitude': item[1], 'longitude':item[2], 'name': item[3]},ignore_index=True)

In [18]:
google_names = google_countries.values[:,3]
not_in_google = []
index = []
for name in es_names:
    try:
        index.append(google_names.tolist().index(name))
    except:
        not_in_google.append(name)

In [19]:
printer()

In [20]:
google_countries

    country   latitude   longitude                               name
0        AD  42.546245    1.601554                            Andorra
1        AE  23.424076   53.847818               United Arab Emirates
2        AF  33.939110   67.709953                        Afghanistan
3        AG  17.060816  -61.796428                Antigua and Barbuda
4        AI  18.220554  -63.068615                           Anguilla
5        AL  41.153332   20.168331                            Albania
6        AM  40.069099   45.038189                            Armenia
7        AN  12.226079  -69.060087               Netherlands Antilles
8        AO -11.202692   17.873887                             Angola
9        AQ -75.250973   -0.071389                         Antarctica
10       AR -38.416097  -63.616672                          Argentina
11       AS -14.270972 -170.132217                     American Samoa
12       AT  47.516231   14.550072                            Austria
13       AU -25.274398  133.775136                          Australia
14       AW  12.521110  -69.968338                              Aruba
15       AZ  40.143105   47.576927                         Azerbaijan
16       BA  43.915886   17.679076             Bosnia and Herzegovina
17       BB  13.193887  -59.543198                           Barbados
18       BD  23.684994   90.356331                         Bangladesh
19       BE  50.503887    4.469936                            Belgium
20       BF  12.238333   -1.561593                       Burkina Faso
21       BG  42.733883   25.485830                           Bulgaria
22       BH  25.930414   50.637772                            Bahrain
23       BI  -3.373056   29.918886                            Burundi
24       BJ   9.307690    2.315834                              Benin
25       BM  32.321384  -64.757370                            Bermuda
26       BN   4.535277  114.727669                             Brunei
27       BO -16.290154  -63.588653                            Bolivia
28       BR -14.235004  -51.925280                             Brazil
29       BS  25.034280  -77.396280                            Bahamas
..      ...        ...         ...                                ...
222      TW  23.697810  120.960515                             Taiwan
223      TZ  -6.369028   34.888822                           Tanzania
224      UA  48.379433   31.165580                            Ukraine
225      UG   1.373333   32.290275                             Uganda
226      UM        NaN         NaN        U.S. Minor Outlying Islands
227      US  37.090240  -95.712891                      United States
228      UY -32.522779  -55.765835                            Uruguay
229      UZ  41.377491   64.585262                         Uzbekistan
230      VA  41.902916   12.453389                       Vatican City
231      VC  12.984305  -61.287228   Saint Vincent and the Grenadines
232      VE   6.423750  -66.589730                          Venezuela
233      VG  18.420695  -64.639968             British Virgin Islands
234      VI  18.335765  -64.896335                U.S. Virgin Islands
235      VN  14.058324  108.277199                            Vietnam
236      VU -15.376706  166.959158                            Vanuatu
237      WF -13.768752 -177.156097                  Wallis and Futuna
238      WS -13.759029 -172.104629                              Samoa
239      XK  42.602636   20.902977                             Kosovo
240      YE  15.552727   48.516388                              Yemen
241      YT -12.827500   45.166244                            Mayotte
242      ZA -30.559482   22.937506                       South Africa
243      ZM -13.133897   27.849332                             Zambia
244      ZW -19.015438   29.154857                           Zimbabwe
245      CW  12.116667  -68.933333                            Curaçao
246      SX  18.033333  -63.050000                       Sint Maarten
247      BQ  12.183333  -68.233333  Bonaire, Sint Eustatius, and Saba
248      AX  60.116667   19.900000                              Åland
249   Empty  18.066667  -63.050000                       Saint Martin
250     Nan  17.900000  -62.833333                   Saint Barthélemy
251      SS   4.850000   31.600000                        South Sudan

[252 rows x 4 columns]

In [23]:
google_countries.to_csv('rkrit_countries.csv',index=False,encoding='utf-8')